import { db } from "@workspace/db";
import { propertiesTable, agentsTable, testimonialsTable } from "@workspace/db";

async function seed() {
  console.log("Seeding agents...");
  const agents = await db.insert(agentsTable).values([
    {
      name: "Sarah Mitchell",
      title: "Senior Property Consultant",
      photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop",
      experience: 12,
      dealsCount: 347,
      rating: 4.9,
      specializations: ["Luxury Homes", "Family Residences", "Investment Properties"],
      phone: "+1 (555) 234-5678",
      whatsapp: "15552345678",
      email: "sarah.mitchell@primerealty.com",
    },
    {
      name: "James Thornton",
      title: "Real Estate Investment Specialist",
      photoUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop",
      experience: 15,
      dealsCount: 512,
      rating: 4.8,
      specializations: ["Commercial Properties", "Investment Strategy", "Market Analysis"],
      phone: "+1 (555) 345-6789",
      whatsapp: "15553456789",
      email: "james.thornton@primerealty.com",
    },
    {
      name: "Priya Sharma",
      title: "Residential Sales Expert",
      photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop",
      experience: 8,
      dealsCount: 218,
      rating: 4.9,
      specializations: ["First-Time Buyers", "Apartments", "Rental Management"],
      phone: "+1 (555) 456-7890",
      whatsapp: "15554567890",
      email: "priya.sharma@primerealty.com",
    },
  ]).returning();

  console.log("Seeding properties...");
  await db.insert(propertiesTable).values([
    {
      title: "Stunning Modern Villa with Pool",
      description: "A beautifully designed modern villa featuring open-plan living spaces, floor-to-ceiling windows, and a heated infinity pool. Perfectly suited for families seeking luxury and comfort in a prime neighbourhood.",
      price: 1250000,
      priceLabel: "$1,250,000",
      listingType: "buy",
      propertyType: "villa",
      bedrooms: 5,
      bathrooms: 4,
      area: 3800,
      areaUnit: "sqft",
      location: "Beverly Hills",
      address: "427 Sunridge Drive, Beverly Hills, CA 90210",
      imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
      ],
      features: ["Infinity Pool", "Home Theater", "Smart Home System", "3-Car Garage", "Gourmet Kitchen", "Wine Cellar"],
      isVerified: true,
      isFeatured: true,
      yearBuilt: 2021,
      parking: true,
      agentId: agents[0].id,
    },
    {
      title: "Elegant Family Home in Prime Location",
      description: "A tasteful 4-bedroom family home on a quiet cul-de-sac with a large private garden. Walking distance to top-rated schools, parks, and local amenities. Move-in ready with high-end finishes throughout.",
      price: 875000,
      priceLabel: "$875,000",
      listingType: "buy",
      propertyType: "house",
      bedrooms: 4,
      bathrooms: 3,
      area: 2600,
      areaUnit: "sqft",
      location: "Palo Alto",
      address: "18 Maple Grove Lane, Palo Alto, CA 94301",
      imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
      ],
      features: ["Large Garden", "Double Garage", "Updated Kitchen", "Master Suite", "Home Office", "Fireplace"],
      isVerified: true,
      isFeatured: true,
      yearBuilt: 2018,
      parking: true,
      agentId: agents[0].id,
    },
    {
      title: "Luxury Downtown Penthouse",
      description: "Exclusive penthouse apartment offering breathtaking panoramic city views from every room. Features a private rooftop terrace, concierge service, and the highest level of finishes. The pinnacle of urban living.",
      price: 2100000,
      priceLabel: "$2,100,000",
      listingType: "buy",
      propertyType: "penthouse",
      bedrooms: 3,
      bathrooms: 3,
      area: 2200,
      areaUnit: "sqft",
      location: "Manhattan",
      address: "One Madison Tower, 55th Floor, New York, NY 10010",
      imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=800&h=600&fit=crop",
      ],
      features: ["Rooftop Terrace", "Panoramic Views", "Concierge", "Private Elevator", "Chef's Kitchen", "Spa Bathroom"],
      isVerified: true,
      isFeatured: true,
      yearBuilt: 2022,
      parking: true,
      agentId: agents[1].id,
    },
    {
      title: "Charming Townhouse near City Centre",
      description: "A well-maintained 3-bedroom townhouse in a sought-after residential community. Contemporary interior design with a cosy rear patio. Excellent transport links and schools nearby.",
      price: 4800,
      priceLabel: "$4,800/mo",
      listingType: "rent",
      propertyType: "townhouse",
      bedrooms: 3,
      bathrooms: 2,
      area: 1650,
      areaUnit: "sqft",
      location: "Austin",
      address: "23 Harmony Row, Austin, TX 78701",
      imageUrl: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
      ],
      features: ["Private Patio", "Modern Kitchen", "In-unit Laundry", "Storage Room", "Pet Friendly"],
      isVerified: true,
      isFeatured: true,
      yearBuilt: 2016,
      parking: true,
      agentId: agents[2].id,
    },
    {
      title: "Contemporary Studio in Arts District",
      description: "A stylish studio apartment in the heart of the Arts District, featuring exposed brick walls, polished concrete floors, and large industrial-style windows. Perfect for young professionals.",
      price: 2200,
      priceLabel: "$2,200/mo",
      listingType: "rent",
      propertyType: "studio",
      bedrooms: 0,
      bathrooms: 1,
      area: 520,
      areaUnit: "sqft",
      location: "Los Angeles",
      address: "88 Artisan Lane, Arts District, Los Angeles, CA 90021",
      imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
      ],
      features: ["Exposed Brick", "High Ceilings", "City Views", "Gym Access", "Rooftop Access"],
      isVerified: true,
      isFeatured: false,
      yearBuilt: 2019,
      parking: false,
      agentId: agents[2].id,
    },
    {
      title: "Spacious Lakefront Apartment",
      description: "Rare lakefront apartment with stunning water views and private balcony. Bright and airy open-plan layout with high-quality finishes. Enjoy morning coffee watching the sunrise over the lake.",
      price: 3500,
      priceLabel: "$3,500/mo",
      listingType: "rent",
      propertyType: "apartment",
      bedrooms: 2,
      bathrooms: 2,
      area: 1100,
      areaUnit: "sqft",
      location: "Chicago",
      address: "Lakeshore Residences, 401 N Lake Shore Dr, Chicago, IL 60611",
      imageUrl: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&h=600&fit=crop",
      images: [
        "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=800&h=600&fit=crop",
        "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=800&h=600&fit=crop",
      ],
      features: ["Lake Views", "Private Balcony", "Doorman", "Gym", "Concierge", "Underground Parking"],
      isVerified: true,
      isFeatured: true,
      yearBuilt: 2020,
      parking: true,
      agentId: agents[1].id,
    },
  ]);

  console.log("Seeding testimonials...");
  await db.insert(testimonialsTable).values([
    {
      clientName: "Marcus & Linda Chen",
      clientPhotoUrl: "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f?w=200&h=200&fit=crop",
      rating: 5,
      comment: "Prime Realty made buying our dream home a genuinely stress-free experience. Sarah walked us through every step, explained the market data clearly, and negotiated an outstanding price. The verified listings gave us total confidence. Highly recommend!",
      transactionType: "bought",
      propertyType: "house",
      date: "February 2026",
    },
    {
      clientName: "Isabelle Fontaine",
      clientPhotoUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
      rating: 5,
      comment: "I was relocating for work and needed to rent quickly. The team at Prime Realty responded immediately, arranged three viewings on the same day, and I was signing my lease within the week. Professional, efficient, and incredibly helpful.",
      transactionType: "rented",
      propertyType: "apartment",
      date: "January 2026",
    },
    {
      clientName: "David & Karen Okafor",
      clientPhotoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
      rating: 5,
      comment: "We sold our family home after 15 years and the experience could not have been better. James provided a detailed market analysis, priced it perfectly, and we received multiple offers above asking price within 10 days. Truly data-driven and professional.",
      transactionType: "sold",
      propertyType: "house",
      date: "March 2026",
    },
    {
      clientName: "Aisha Rahman",
      clientPhotoUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&h=200&fit=crop",
      rating: 5,
      comment: "As a first-time buyer, I was nervous about the whole process. Priya at Prime Realty was patient, knowledgeable, and always available to answer my questions. The free valuation service was incredibly valuable. I felt informed and confident throughout.",
      transactionType: "bought",
      propertyType: "apartment",
      date: "February 2026",
    },
  ]);

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
